name: login_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
    
  # Firebase & Authentication
  # These packages handle user authentication and Firebase services
  firebase_core: ^3.12.1       # Core Firebase App functionality
  firebase_auth: ^5.5.1        # Authentication services (login, register, password reset)
  google_sign_in: ^6.3.0       # Google account authentication support
  firebase_messaging: ^15.2.4  # Push notification handling via Firebase Cloud Messaging

  # UI Components
  # Packages that enhance the user interface and interactions
  cupertino_icons: ^1.0.8      # iOS-style icons
  url_launcher: ^6.1.14        # Launch external URLs (web, phone, email)
  fluttertoast: ^8.2.2         # Toast notifications
  video_player: ^2.8.2         # Video playback for widget examples
  flutter_local_notifications: ^16.2.0  # Local system notifications

  # Data Storage
  # Local data persistence solutions
  shared_preferences: ^2.2.2   # Simple key-value storage for app settings
  hive: ^2.2.3                 # NoSQL database for complex data storage
  hive_flutter: ^1.1.0         # Flutter integration for Hive

  # Networking
  # API communication and data fetching
  dio: ^5.4.0                  # Advanced HTTP client for API requests
  web_socket_channel: ^2.4.0   # WebSocket connections for real-time communication

  # App Configuration
  # Used for app configuration and customization
  flutter_launcher_icons: ^0.14.3  # App icon generation and configuration

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Code Generation & Development Tools
  hive_generator: ^2.0.1       # Code generation for Hive data models
  build_runner: ^2.4.6         # Dart code generation and build system
  flutter_lints: ^5.0.0        # Lint rules to encourage good coding practices

flutter:
  uses-material-design: true
  assets:
    - assets/

# App Icon Configuration
# Automatically generates app icons for different platforms and resolutions
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
