// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy8Fk1y8jni7e3_GkR4P4iA6T0KRjDmHQ',
    appId: '1:764272310427:web:2be5cd858381050e5dae3e',
    messagingSenderId: '764272310427',
    projectId: 'flutterauth-feedc',
    authDomain: 'flutterauth-feedc.firebaseapp.com',
    storageBucket: 'flutterauth-feedc.firebasestorage.app',
    measurementId: 'G-9ENVXGJTVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJaH-4o3zbqb966bPSsGWTnmP3wDeBBeA',
    appId: '1:764272310427:android:17d3a75082b1dcf75dae3e',
    messagingSenderId: '764272310427',
    projectId: 'flutterauth-feedc',
    storageBucket: 'flutterauth-feedc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIYjymMJ5DGWNp5jyX8mTod0niHPa1wy8',
    appId: '1:764272310427:ios:f221cd6d1fcf83fd5dae3e',
    messagingSenderId: '764272310427',
    projectId: 'flutterauth-feedc',
    storageBucket: 'flutterauth-feedc.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIYjymMJ5DGWNp5jyX8mTod0niHPa1wy8',
    appId: '1:764272310427:ios:f221cd6d1fcf83fd5dae3e',
    messagingSenderId: '764272310427',
    projectId: 'flutterauth-feedc',
    storageBucket: 'flutterauth-feedc.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy8Fk1y8jni7e3_GkR4P4iA6T0KRjDmHQ',
    appId: '1:764272310427:web:7f1e9bd63a91174e5dae3e',
    messagingSenderId: '764272310427',
    projectId: 'flutterauth-feedc',
    authDomain: 'flutterauth-feedc.firebaseapp.com',
    storageBucket: 'flutterauth-feedc.firebasestorage.app',
    measurementId: 'G-0J08KLFPND',
  );
}
